### ISSUE TITLE
Can I use this script in my mods?

### ISSUE THREAD

**Issue by MarcusModding** [stijnwop/tirePressure#1]
Hi there,

I came across your tire pressure script by accident and would like to ask you whether I can incorporate this into my mods and may also publish it.

If so, is it still possible to display an ad in a vehicle?

PS: sorry, was translated with google translate.

greeting
Marcus

**Comment by stijnwop** [comment]
Yes Marcus, thats why it's public.

**Comment by MarcusModding** [comment]
Thanks
