### ISSUE TITLE
Binding Error

### ISSUE THREAD

**Issue by racer001** [stijnwop/tirePressure#3]
Hey

First of all great script! Thanks for it!

Now the problem
If more Vehicles had the Script installed (everyone works fine) you get binding errors spamed in the log like this:

  Warning: Tried assigning the binding [(BUTTON_7, BUTTON_20), deviceId: 0_044F-B66E-1D00-XFw/XEhJRCNWSURfMDQ0RiZQSURfQjY2RSM2JmJjZTRhODQmMSYwMDAwI3s0ZDFlNTViMi1mMTZmLTExY2YtODhjYi0wMDExMTEwMDAwMzB9AA==, axisComponent: +, index: 1, isActive: true, isShadowed: false isInverted: nil, isDown: false, isUp: false, inputValue: 0] to TP_AXIS_PRESSURE to an occupied slot. The new binding has been ignored
  Warning: Tried assigning the binding [(BUTTON_7, BUTTON_18), deviceId: 0_044F-B66E-1D00-XFw/XEhJRCNWSURfMDQ0RiZQSURfQjY2RSM2JmJjZTRhODQmMSYwMDAwI3s0ZDFlNTViMi1mMTZmLTExY2YtODhjYi0wMDExMTEwMDAwMzB9AA==, axisComponent: -, index: 1, isActive: true, isShadowed: false isInverted: nil, isDown: false, isUp: false, inputValue: 0] to TP_AXIS_PRESSURE to an occupied slot. The new binding has been ignored
  Warning: Tried assigning the binding [(KEY_lctrl, KEY_pageup), deviceId: KB_MOUSE_DEFAULT, axisComponent: +, index: 1, isActive: true, isShadowed: false isInverted: nil, isDown: false, isUp: false, inputValue: 0] to TP_AXIS_PRESSURE to an occupied slot. The new binding has been ignored
  Warning: Tried assigning the binding [(KEY_lctrl, KEY_pagedown), deviceId: KB_MOUSE_DEFAULT, axisComponent: -, index: 1, isActive: true, isShadowed: false isInverted: nil, isDown: false, isUp: false, inputValue: 0] to TP_AXIS_PRESSURE to an occupied slot. The new binding has been ignored
  Warning: Tried assigning the binding [(KEY_lalt), deviceId: KB_MOUSE_DEFAULT, axisComponent: +, index: 1, isActive: true, isShadowed: false isInverted: nil, isDown: false, isUp: false, inputValue: 0] to TP_TOGGLE_PRESSURE to an occupied slot. The new binding has been ignored
  Warning: Tried assigning the binding [(BUTTON_7), deviceId: 0_044F-B66E-1D00-XFw/XEhJRCNWSURfMDQ0RiZQSURfQjY2RSM2JmJjZTRhODQmMSYwMDAwI3s0ZDFlNTViMi1mMTZmLTExY2YtODhjYi0wMDExMTEwMDAwMzB9AA==, axisComponent: +, index: 1, isActive: true, isShadowed: false isInverted: nil, isDown: false, isUp: false, inputValue: 0] to TP_TOGGLE_PRESSURE to an occupied slot. The new binding has been ignored
  Warning: Tried assigning the binding [(BUTTON_7, BUTTON_20), deviceId: 0_044F-B66E-1D00-XFw/XEhJRCNWSURfMDQ0RiZQSURfQjY2RSM2JmJjZTRhODQmMSYwMDAwI3s0ZDFlNTViMi1mMTZmLTExY2YtODhjYi0wMDExMTEwMDAwMzB9AA==, axisComponent: +, index: 1, isActive: true, isShadowed: false isInverted: nil, isDown: false, isUp: false, inputValue: 0] to TP_AXIS_PRESSURE to an occupied slot. The new binding has been ignored
  Warning: Tried assigning the binding [(BUTTON_7, BUTTON_18), deviceId: 0_044F-B66E-1D00-XFw/XEhJRCNWSURfMDQ0RiZQSURfQjY2RSM2JmJjZTRhODQmMSYwMDAwI3s0ZDFlNTViMi1mMTZmLTExY2YtODhjYi0wMDExMTEwMDAwMzB9AA==, axisComponent: -, index: 1, isActive: true, isShadowed: false isInverted: nil, isDown: false, isUp: false, inputValue: 0] to TP_AXIS_PRESSURE to an occupied slot. The new binding has been ignored

More vehicles with the script = more of this errors and binding option ingame (options -> keysettings)

Hope it can be fixed!
Grettings
Racer001

**Comment by stijnwop** [comment]
Report it to giants.. nothing I can do about it really.
